services:
  webserver:
    image: tugboatqa/php-nginx:8.3-fpm-trixie
    default: true
    depends: database
    commands:
      init:
        - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        - apt-get update && apt-get install -y libzip-dev zip jq libpng-dev libjpeg-dev libfreetype6-dev libwebp-dev libwebp7 webp libmagickwand-dev imagemagick webp libmagickcore-dev libmagickwand-dev nodejs
        - docker-php-ext-install opcache
        - docker-php-ext-install zip
        - docker-php-ext-enable zip
        - docker-php-ext-configure gd --with-jpeg --with-freetype
        - docker-php-ext-install gd
        - docker-php-ext-enable imagick
        - echo "upload_max_filesize=100M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - echo "post_max_size=100M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - echo "memory_limit=512M" >> /usr/local/etc/php/conf.d/tugboat.ini
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
      update:
      build:

  database:
    image: tugboatqa/mariadb:10.6
    commands:
      init:
        - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'tugboat'; FLUSH PRIVILEGES;"
